---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-enterprise-crds
  namespace: linkerd
spec:
  chart:
    spec:
      chart: linkerd-enterprise-crds
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: linkerd-buoyant
      version: "2.19.0"
  interval: 15m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-enterprise-control-plane
  namespace: linkerd
spec:
  install:
    createNamespace: false
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  chart:
    spec:
      chart: linkerd-enterprise-control-plane
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: linkerd-buoyant
      version: "2.19.0"
  interval: 15m0s
  dependsOn:
  - name: linkerd-enterprise-crds
    namespace: linkerd
  values:
    licenseSecret: buoyant-license
  valuesFrom:
  - kind: Secret
    name: linkerd-certs
    valuesKey: ca.crt
    targetPath: identityTrustAnchorsPEM
  - kind: Secret
    name: linkerd-certs
    valuesKey: issuer.crt
    targetPath: identity.issuer.tls.crtPEM
  - kind: Secret
    name: linkerd-certs
    valuesKey: issuer.key
    targetPath: identity.issuer.tls.keyPEM
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-buoyant
  namespace: linkerd-buoyant
spec:
  install:
    createNamespace: false
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  chart:
    spec:
      chart: linkerd-buoyant
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: linkerd-buoyant
      version: "2.19.0"
  interval: 15m0s
  values:
    licenseSecret: buoyant-license 